#!/usr/bin/env python2

#importing pillow library
from PIL import Image
#importing pytesseract library
import pytesseract
#importing sys module to take input
import sys



#open the image that is going to be read 
#and store it in a variable
im = Image.open(sys.argv[1])
#storing output from pytesseract function 
#in a variable
text = pytesseract.image_to_string(im, lang="eng")
print(text)
