#!/usr/bin/env python3

#importing pillow library
from PIL import Image
#importing pytesseract library
import pytesseract
#importing sys module
import sys


#enter the filepath to the image and it will be
#passed in to the function as argv[1]
im = Image.open(sys.argv[1])
#storing output from pytesseract function 
#in a variable
text = pytesseract.image_to_string(im, lang="eng")
print(text)

